FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    ansible \
    ssh \
    postgresql-client \
    && apt-get clean

WORKDIR /ansible

COPY ansible/ /ansible/

ENTRYPOINT ["ansible-playbook", "/ansible/site.yml", "-i", "localhost,", "--connection=local"]
