version: "3.8"

services:
  db:
    image: postgres:15
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  init:
    build:
      context: .
      dockerfile: Dockerfile.ansible
    env_file:
      - .env
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:80"
    depends_on:
      - init
    volumes:
      - ./ansible/templates:/app/templates # for templates/
      #- ./ansible/templates/templates/:/app/templates # for templates/templates
      - ./ansible/templates/app.py.j2:/app/app.py  # for live editing (optional)

volumes:
  pgdata:
